# Use the official Python image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the application files
COPY main.py .

# Command to run the script
CMD ["python", "main.py"]
